export const GREETINGS = [
	"Hi there! I'm Sprucebot 🌲🤖! Here are some things can help you with:",
	'Hey! My name is Sprucebot 🌲🤖! Let me know which of the following you want to discuss:',
	'Hello! You can call me Sprucebot 🌲🤖 and I can help you with:',
	'Hi there! You can call me Sprucebot 🌲🤖! Need something? I can help with:',
	'Greetings! My name is Sprucebot 🌲🤖. Below are some things I can help you with:',
	"Hello there! I'm Sprucebot 🌲🤖 and the things I can help with are:",
	'Hey there! My name is Sprucebot 🌲🤖 and I can help you with:',
	"Good to see you! I'm Sprucebot 🌲🤖 and this is the list of things I'm ready to help with:",
	'Hey! You can call me Sprucebot 🌲🤖 and ask be about anything below:',
	'Hi! My name is Sprucebot 🌲🤖! Need help? Here are the things I can help with:',
	"Hi there! My name is Sprucebot 🌲🤖 and I'm at your service, as long as it has to do with the following:",
	'Hey there! You can call me Sprucebot 🌲🤖. I can help you with:',
	"Hello! My name is Sprucebot 🌲🤖. If you need help with any of the following, I'm your bot!",
	"Howdy! I'm Sprucebot 🌲🤖 and this is the list of my specialties:",
	'Hiya! You can call me Sprucebot 🌲🤖! Need any help with the following?',
	'Hello there! You can call me Sprucebot 🌲🤖. I can help you with:',
	'Good to see you! My name is Sprucebot 🌲🤖. Here are some of my favorite things:',
	'Greetings! You can call me Sprucebot 🌲🤖. Which would you like to talk about?',
	'Hey there! My name is Sprucebot 🌲🤖. Here are the things I can help you with:',
	"Hi! You can call me Sprucebot 🌲🤖!! I can't wait to help you with the following:",
]
