export const GREETINGS = [
	"Hi there! I'm Sprucebot 🌲🤖",
	'Hey! My name is Sprucebot 🌲🤖',
	'Hello! You can call me Sprucebot 🌲🤖',
	'Hi there! You can call me Sprucebot 🌲🤖',
	'Greetings! My name is Sprucebot 🌲🤖',
	"Hello there! I'm Sprucebot 🌲🤖",
	'Hey there! My name is Sprucebot 🌲🤖',
	"Good to see you! I'm Sprucebot 🌲🤖",
	'Hey! You can call me Sprucebot 🌲🤖',
	'Hi! My name is Sprucebot 🌲🤖',
	'Hi there! My name is Sprucebot 🌲🤖',
	'Hey there! You can call me Sprucebot 🌲🤖',
	'Hello! My name is Sprucebot 🌲🤖',
	"Howdy! I'm Sprucebot 🌲🤖",
	'Hiya! You can call me Sprucebot 🌲🤖',
	'Hello there! You can call me Sprucebot 🌲🤖',
	'Good to see you! My name is Sprucebot 🌲🤖',
	'Greetings! You can call me Sprucebot 🌲🤖',
	'Hey there! My name is Sprucebot 🌲🤖',
	'Hi! You can call me Sprucebot 🌲🤖',
]
